apiVersion: v1
kind: Namespace
metadata:
  name: vci-flux-secret-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-platform-flux-secret-controller
  namespace: vci-flux-secret-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcluster-platform-flux-secret-controller
rules:
  - apiGroups: ["management.loft.sh"]
    resources: ["virtualclusterinstances", "virtualclusterinstances/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.loft.sh"]
    resources: ["accesskeys"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch","update"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-platform-flux-secret-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcluster-platform-flux-secret-controller
subjects:
  - kind: ServiceAccount
    name: vcluster-platform-flux-secret-controller
    namespace: vci-flux-secret-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcluster-platform-flux-secret-controller
  namespace: vci-flux-secret-controller
  labels:
    app: vcluster-platform-flux-secret-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcluster-platform-flux-secret-controller
  template:
    metadata:
      labels:
        app: vcluster-platform-flux-secret-controller
    spec:
      serviceAccountName: vcluster-platform-flux-secret-controller
      containers:
        - name: manager
          image: ghcr.io/loft-demos/vcluster-platform-flux-secret-controller:sha-512afa1
          imagePullPolicy: IfNotPresent
          args:
            - "--selector=vcluster.com/import-fluxcd=true"
            - "--secret-key=value"
            - "--secret-name-prefix=vci-"
            - "--server-template=https://{{ .Domain }}/kubernetes/project/{{ .Project }}/virtualcluster/{{ .Name }}"
            - "--loft-domain=beta.us.demo.dev"
            - "--flux-namespaces=flux-*"
            - "--controller-namespace=vci-flux-secret-controller"
            - "--accesskey-type=User"
            - "--accesskey-team=loft-admins"
            - "--zap-log-level=debug"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
